backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: 'Upload "{{path}}"'
    deleteMedia: 'Delete "{{path}}"'

# Media settings
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
media_library:
  name: "uploadcare" # Required property for media_library
  max_file_size: 5000000 # in bytes, 5MB

# Editorial workflow
# Uncomment this to enable drafts and review process
# publish_mode: editorial_workflow

# Site admin customization
local_backend: true
display_url: https://jpr-contracting.netlify.app
logo_url: /images/JPR-contracting_din_r2.png

# Content collections
collections:
  # ===== WEBSITE SETTINGS =====
  - name: "settings"
    label: "Website Settings"
    files:
      - file: "hugo.yaml"
        label: "General Settings"
        name: "general"
        editor:
          preview: false
        fields:
          - {label: "Site Title", name: "title", widget: "string", hint: "The name of the website that appears in browser tabs"}
          - {label: "Base URL", name: "baseURL", widget: "string", hint: "The website domain (e.g., https://jpr-contracting.com)"}
          - {label: "Language", name: "languageCode", widget: "string", default: "en-us"}
          
          - label: "Site Parameters"
            name: "params"
            widget: "object"
            fields:
              - {label: "Site Description", name: "description", widget: "text", hint: "A brief description of the business for search engines"}
              - {label: "Logo", name: "logo", widget: "image", hint: "The company logo (SVG or PNG recommended)"}
              - {label: "Email", name: "email", widget: "string", hint: "Primary contact email address"}
              - {label: "Phone", name: "phone", widget: "string", hint: "Primary contact phone number"}
              - {label: "Address", name: "address", widget: "text", hint: "Business physical address"}
              
              - label: "Social Media"
                name: "social"
                widget: "object"
                fields:
                  - {label: "Facebook", name: "facebook", widget: "string", required: false, hint: "Facebook page URL (leave blank if not used)"}
                  - {label: "Instagram", name: "instagram", widget: "string", required: false, hint: "Instagram profile URL (leave blank if not used)"}
                  - {label: "Twitter", name: "twitter", widget: "string", required: false, hint: "Twitter profile URL (leave blank if not used)"}
                  - {label: "LinkedIn", name: "linkedin", widget: "string", required: false, hint: "LinkedIn profile URL (leave blank if not used)"}
  
  # ===== SERVICES SECTION SETTINGS =====
  - name: "services_section"
    label: "Services Section Settings"
    files:
      - file: "hugo.yaml"
        label: "Services Section"
        name: "services_section"
        editor:
          preview: false
        fields:
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", hint: "Heading for the services section"}
              - {label: "Section Description", name: "description", widget: "text", hint: "Brief introduction for the services section"}
  
  # ===== SERVICES =====
  - name: "services"
    label: "Services"
    folder: "data/services"
    create: true
    extension: "yml"
    format: "yml"
    slug: "{{fields.id}}"
    summary: "{{title}}"
    editor:
      preview: false
    fields:
      - {label: "ID", name: "id", widget: "string", hint: "Short name used for URL and references (e.g., bathroom-remodels)"}
      - {label: "Title", name: "title", widget: "string", hint: "Service name as it will appear on the website"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief summary of this service (appears in listings)"}
      - {label: "Featured Image", name: "image", widget: "image", hint: "Main image representing this service"}
      - label: "Service Details"
        name: "features"
        widget: "list"
        hint: "List of key features or services offered (bullet points) (Separate with commas)"
        default: []
      - {label: "Weight", name: "weight", widget: "number", value_type: "int", default: 50, hint: "Display order (lower numbers appear first)"}

  # ===== PROJECTS =====
  - name: "projects"
    label: "Projects & Portfolio"
    folder: "data/projects"
    create: true
    extension: "yml"
    format: "yml"
    slug: "{{slug}}"
    summary: "{{title}} ({{location}})"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Name of the project"}
      - {label: "Category", name: "category", widget: "list", hint: "Project categories (e.g., Framing, Siding, etc.) For filtering projects in the portfolio. (Try to use existing category names from other projects that are relevant to this project)"}
      - {label: "Location", name: "location", widget: "string", hint: "Project location (city/neighborhood)"}
      - {label: "Completion Date", name: "date", widget: "datetime", date_format: "MMM YYYY", format: "MMM YYYY", hint: "When the project was completed"}
      - {label: "Description", name: "description", widget: "text", hint: "Brief description of the project and results"}
      - label: "Project Gallery"
        name: "gallery"
        widget: "list"
        summary: '{{fields.image}}'
        hint: "All project images (The first image will be the featured cover image)"
        field: {label: "Image", name: "image", widget: "image"}
      - label: "Client Testimonial"
        name: "testimonial"
        widget: "object"
        required: false
        hint: "Optional testimonial from the client for this project"
        fields:
          - {label: "Quote", name: "quote", widget: "text", required: false, hint: "Client testimonial text"}
          - {label: "Client Name", name: "author", widget: "string", required: false, hint: "Name of the client who provided this testimonial"}

  # ===== TESTIMONIALS =====
  - name: "testimonials"
    label: "Testimonials"
    folder: "data/testimonials"
    create: true
    extension: "yml"
    format: "yml"
    slug: "{{fields.name | slugify}}"
    editor:
      preview: false
    fields:
      - {label: "Client Name", name: "name", widget: "string", hint: "Name of the person providing the testimonial"}
      - {label: "Location", name: "location", widget: "string", hint: "City or neighborhood of the client"}
      - {label: "Client Image", name: "image", widget: "image", required: false, hint: "Optional photo of the client"}
      - {label: "Testimonial", name: "quote", widget: "text", hint: "The testimonial text from the client"}
      - {label: "Project", name: "project", widget: "string", required: false, hint: "Optional - which project this testimonial is about"}
      - {label: "Rating", name: "rating", widget: "number", required: false, value_type: "int", min: 1, max: 5, default: 5, hint: "Client rating (1-5 stars)"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, hint: "Should this testimonial appear on the homepage?"}

  # ===== FAQs =====
  - name: "faqs"
    label: "FAQs"
    folder: "data/faqs"
    create: true
    extension: "yml"
    format: "yml"
    slug: "{{fields.question | slugify}}"
    editor:
      preview: false
    fields:
      - {label: "Question", name: "question", widget: "string", hint: "The frequently asked question"}
      - {label: "Answer", name: "answer", widget: "markdown", hint: "The answer to the question"}
      - {label: "Weight", name: "weight", widget: "number", value_type: "int", required: false, hint: "Order of appearance (lower numbers first)"}

  # ===== PROCESS STEPS =====
  - name: "process"
    label: "Service Process"
    files:
      - file: "data/process_steps.yml"
        label: "Process Steps"
        name: "process_steps"
        editor:
          preview: false
        fields:
          - label: "Process Overview"
            name: "overview"
            widget: "text"
            hint: "Brief description of your overall service process"
          - label: "Steps"
            name: "steps"
            widget: "list"
            summary: "{{fields.id}}. {{fields.title}}"
            hint: "The steps in your service process, from start to finish"
            fields:
              - {label: "Step Number", name: "id", widget: "number", value_type: "int", hint: "Step order (1, 2, 3, etc.)"}
              - {label: "Step Title", name: "title", widget: "string", hint: "Name of this process step"}
              - {label: "Description", name: "description", widget: "text", hint: "Detailed explanation of what happens in this step"}

  # ===== FORMS =====
  - name: "forms"
    label: "Forms"
    files:
      - file: "data/contact_form.yml"
        label: "Contact Form"
        name: "contact"
        editor:
          preview: false
        fields:
          - {label: "Success Message", name: "success_message", widget: "string", hint: "Message shown after form submission"}
          - {label: "Email Recipient", name: "recipient_email", widget: "string", hint: "Email address that receives form submissions"}
          - label: "Form Fields"
            name: "fields"
            widget: "list"
            fields:
              - {label: "Field Label", name: "label", widget: "string", hint: "The visible label for this field"}
              - {label: "Field Name", name: "name", widget: "string", hint: "Technical identifier for this field (e.g., 'email')"}
              - {label: "Field Type", name: "type", widget: "select", options: ["text", "email", "tel", "textarea", "select"], default: "text"}
              - {label: "Required", name: "required", widget: "boolean", default: true, hint: "Is this field mandatory?"}
              - {label: "Placeholder", name: "placeholder", widget: "string", required: false, hint: "Example text that appears in the empty field"} 
